import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Save, ArrowLeft, Package, Building2, MapPin, Plus, Trash2, User, Wrench, Hash, CheckCircle, AlertCircle, Loader, Lightbulb } from 'lucide-react';
import apiService from '../services/apiService';
import SearchableDropdown from '../components/SearchableDropdown';
import ConfirmationModal from '../components/ConfirmationModal';

const AddAsset = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  
  // Modal states
  const [showCreateConfirmation, setShowCreateConfirmation] = useState(false);
  const [showCancelConfirmation, setShowCancelConfirmation] = useState(false);
  
  // State tracking for intelligent error handling
  const [userHasInteracted, setUserHasInteracted] = useState(false);
  const [projectSearchError, setProjectSearchError] = useState(null);
  
  // Auto-populated project data
  const [projectData, setProjectData] = useState({
    project_reference_num: '',
    customer_name: '',
    customer_reference_number: '',
    project_title: ''
  });
  
  // Dropdowns data
  const [availableProjects, setAvailableProjects] = useState([]);
  const [filteredProjects, setFilteredProjects] = useState([]);
  const [projectSearchTerm, setProjectSearchTerm] = useState('');
  const [showProjectDropdown, setShowProjectDropdown] = useState(false);
  const [branches, setBranches] = useState([]);
  const [recipients, setRecipients] = useState([]);
  const [categories, setCategories] = useState([]);
  const [models, setModels] = useState([]);
  const [peripheralTypes, setPeripheralTypes] = useState([]);

  // Modal states for adding new options dynamically
  const [showAddModal, setShowAddModal] = useState(false);
  const [modalType, setModalType] = useState(''); // 'category', 'model', 'peripheral', 'windows', 'office', 'antivirus', 'software'
  const [newOptionValue, setNewOptionValue] = useState('');
  const [addingOption, setAddingOption] = useState(false);

  // Dropdown options for new fields
  const [windowsOptions, setWindowsOptions] = useState([]);
  const [officeOptions, setOfficeOptions] = useState([]);
  const [antivirusOptions, setAntivirusOptions] = useState([]);
  const [softwareOptions, setSoftwareOptions] = useState([]);
  
  // Form data
  const [selectedBranch, setSelectedBranch] = useState('');
  
  // Main asset form data
  const [asset, setAsset] = useState({
    serial_number: '',
    tag_id: '',
    item_name: '',
    category: '',
    model: '',
    status: 'Active',
    recipient_name: '',
    department_name: '',
    position: '',
    windows: '',
    microsoft_office: '',
    antivirus: '',
    software: '',
    monthly_prices: ''
  });

  // Peripheral data
  const [peripherals, setPeripherals] = useState([{
    peripheral_name: '',
    serial_code_name: '',
    condition: 'Good',
    remarks: ''
  }]);

  // Auto-generated fields (read-only)
  const [autoGenerated, setAutoGenerated] = useState({
    asset_id: 'Will be auto-generated',
    pmid: 'Will be auto-generated',
    inventory_id: 'Will be auto-generated'
  });

  // Fetch initial data on mount
  useEffect(() => {
    fetchAvailableProjects();
    fetchRecipients();
    fetchCategories();
    fetchModels();
    fetchPeripheralTypes();
    fetchWindowsOptions();
    fetchOfficeOptions();
    fetchAntivirusOptions();
    fetchSoftwareOptions();
  }, []);

  // Filter projects based on search term
  useEffect(() => {
    if (projectSearchTerm.trim() === '') {
      setFilteredProjects(availableProjects);
    } else {
      const filtered = availableProjects.filter(project => 
        project.Project_Ref_Number.toLowerCase().includes(projectSearchTerm.toLowerCase()) ||
        project.Project_Title.toLowerCase().includes(projectSearchTerm.toLowerCase()) ||
        project.Customer_Name?.toLowerCase().includes(projectSearchTerm.toLowerCase())
      );
      setFilteredProjects(filtered);
    }
  }, [projectSearchTerm, availableProjects]);

  // Auto-populate project data when project reference number changes
  useEffect(() => {
    if (projectData.project_reference_num.trim()) {
      // Only fetch if we don't already have the customer name (meaning data wasn't populated from dropdown)
      if (!projectData.customer_name) {
        fetchProjectByReference(projectData.project_reference_num);
      }
    } else {
      // Clear dependent data when project ref is cleared
      setBranches([]);
      setSelectedBranch('');
      setProjectData(prev => ({
        project_reference_num: prev.project_reference_num,
        customer_name: '',
        customer_reference_number: '',
        project_title: ''
      }));
    }
  }, [projectData.project_reference_num]);

  // Fetch branches when customer name is populated
  useEffect(() => {
    if (projectData.customer_name) {
      fetchBranchesByCustomer(projectData.customer_name);
    }
  }, [projectData.customer_name]);

  const fetchAvailableProjects = async () => {
    try {
      setLoading(true);
      // Fetch all projects without pagination (use high limit to get all)
      const response = await apiService.getAllProjects(1, 1000);
      console.log('Available projects response:', response);
      
      // Handle both paginated and direct array responses
      let projects = [];
      if (response.data) {
        // If it's a paginated response with data property
        projects = Array.isArray(response.data) ? response.data : [];
      } else if (Array.isArray(response)) {
        // If it's a direct array
        projects = response;
      }
      
      console.log(`✅ Loaded ${projects.length} projects`);
      setAvailableProjects(projects);
      setFilteredProjects(projects);
      setProjectSearchError(null); // Clear search-specific errors
    } catch (err) {
      console.error('Error fetching available projects:', err);
      
      // Only set error if user has actually interacted with the search
      if (userHasInteracted) {
        setProjectSearchError('Failed to load available projects');
      }
      
      // Set mock data as fallback (always available)
      const mockProjects = [
        {
          Project_ID: 1,
          Project_Ref_Number: 'QT240000000015729',
          Project_Title: 'PERKHIDMATAN SEWAAN PERKAKASAN ICT,PENYELENGGARAAN KOMPREHENSIF DAN BANTUAN SOKONGAN BAGI TEMPOH 37 BULAN DI AGENSI PENGURUSAN BENCANA NEGARA (NADMA)',
          Customer_Name: 'NADMA'
        },
        {
          Project_ID: 6,
          Project_Ref_Number: 'QT240000000029575',
          Project_Title: 'PERKHIDMATAN SEWAAN PERALATAN ICT DI INSTITUT LATIHAN ISLAM MALAYSIA (ILIM)',
          Customer_Name: 'ILIM'
        },
        {
          Project_ID: 8,
          Project_Ref_Number: 'QT244567890987',
          Project_Title: 'PERKHIDMATAN SEWAAN PERALATAN ICT DI MAHKAMAH SYARIAH WILAYAH PERSEKUTUAN KUALA LUMPUR',
          Customer_Name: 'MSWP'
        }
      ];
      console.log('⚠️ Using fallback mock projects');
      setAvailableProjects(mockProjects);
      setFilteredProjects(mockProjects);
    } finally {
      setLoading(false);
    }
  };

  const fetchProjectByReference = async (projectRefNum) => {
    try {
      console.log('🔄 Fetching project by reference:', projectRefNum);
      setLoading(true);
      const response = await apiService.getProjectByReference(projectRefNum);
      console.log('✅ Project response received:', response);
      
      if (response.data) {
        setProjectData(prev => ({
          ...prev,
          customer_name: response.data.customer_name,
          customer_reference_number: response.data.customer_reference_number,
          project_title: response.data.project_title
        }));
        
        // Auto-populate antivirus from project
        if (response.data.antivirus) {
          console.log('🦠 Auto-populating antivirus from project:', response.data.antivirus);
          setAsset(prev => ({
            ...prev,
            antivirus: response.data.antivirus
          }));
        } else {
          console.log('⚠️ No antivirus data in project response');
        }
        
        console.log('✅ Project data populated:', response.data);
        setError(null);
        
        // Automatically fetch branches when customer is found
        if (response.data.customer_name) {
          console.log('🔄 Auto-fetching branches for customer:', response.data.customer_name);
          await fetchBranchesByCustomer(response.data.customer_name);
        }
      } else {
        console.warn('⚠️ No project found for reference:', projectRefNum);
        setError(`No project found with reference number "${projectRefNum}"`);
      }
    } catch (err) {
      console.error('❌ Error fetching project:', err);
      console.error('❌ Error details:', {
        message: err.message,
        stack: err.stack,
        projectRefNum
      });
      setError(`Failed to load project "${projectRefNum}". ${err.message || 'Please check the reference number and try again.'}`);
      // Clear dependent fields
      setProjectData(prev => ({
        ...prev,
        customer_name: '',
        customer_reference_number: '',
        project_title: ''
      }));
      setBranches([]);
    } finally {
      setLoading(false);
    }
  };

  const fetchBranchesByCustomer = async (customerName) => {
    try {
      console.log('🔄 Fetching branches for customer:', customerName);
      console.log('🔍 Customer name type:', typeof customerName);
      console.log('🔍 Customer name exact value:', JSON.stringify(customerName));
      setLoading(true);
      
      const response = await apiService.getBranchesByCustomer(customerName);
      console.log('✅ Branch response received:', response);
      
      const branches = response.data || [];
      setBranches(branches);
      
      if (branches.length === 0) {
        console.warn('⚠️ No branches found for customer:', customerName);
        
        // Provide fallback branches if none found
        const fallbackBranches = [
          {
            Customer_ID: 'temp_1',
            Customer_Ref_Number: 'TEMP-001',
            Customer_Name: customerName,
            Branch: 'Head Office'
          },
          {
            Customer_ID: 'temp_2',
            Customer_Ref_Number: 'TEMP-002',
            Customer_Name: customerName,
            Branch: 'Branch Office'
          }
        ];
        
        setBranches(fallbackBranches);
        setError(`Using default branches for "${customerName}". No specific branches found in database.`);
        
        console.log('📋 Using fallback branches:', fallbackBranches);
      } else {
        console.log(`✅ Found ${branches.length} branches for ${customerName}`);
        setError(null); // Clear any previous errors
      }
      
    } catch (err) {
      console.error('❌ Error fetching branches:', err);
      console.error('❌ Error details:', {
        message: err.message,
        stack: err.stack,
        customerName
      });
      
      // Provide fallback branches on error
      const fallbackBranches = [
        {
          Customer_ID: 'fallback_1',
          Customer_Ref_Number: 'FB-001',
          Customer_Name: customerName,
          Branch: 'Main Office'
        },
        {
          Customer_ID: 'fallback_2',
          Customer_Ref_Number: 'FB-002',
          Customer_Name: customerName,
          Branch: 'Secondary Office'
        }
      ];
      
      setBranches(fallbackBranches);
      setError(`Branch loading failed for "${customerName}". Using default options. (${err.message || 'Network error'})`);
      
      console.log('📋 Using fallback branches due to error:', fallbackBranches);
    } finally {
      setLoading(false);
    }
  };



  const fetchRecipients = async () => {
    try {
      const response = await apiService.getRecipients();
      setRecipients(response.data || []);
    } catch (err) {
      console.error('Error fetching recipients:', err);
      setRecipients([]);
    }
  };

  const fetchCategories = async () => {
    try {
      const response = await apiService.getCategories();
      const categoriesData = response.data || [];
      
      // Check if backend is returning fallback data
      if (response.fallback) {
        console.warn('⚠️ Backend returned FALLBACK categories (database error)');
      }
      
      setCategories(categoriesData);
      return categoriesData;
    } catch (err) {
      console.error('Error fetching categories:', err);
      setCategories([]);
      return [];
    }
  };

  const fetchModels = async () => {
    try {
      const response = await apiService.getModels();
      const modelsData = response.data || [];
      setModels(modelsData);
      return modelsData;
    } catch (err) {
      console.error('Error fetching models:', err);
      setModels([]);
      return [];
    }
  };

  const fetchPeripheralTypes = async () => {
    try {
      const response = await apiService.getPeripheralTypes();
      const typesData = response.data || [];
      setPeripheralTypes(typesData);
      return typesData;
    } catch (err) {
      console.error('Error fetching peripheral types:', err);
      setPeripheralTypes([]);
      return [];
    }
  };

  const fetchWindowsOptions = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/v1/options/windows');
      const result = await response.json();
      const optionsData = result.data || [];
      setWindowsOptions(optionsData);
      return optionsData;
    } catch (err) {
      console.error('Error fetching Windows options:', err);
      setWindowsOptions([]);
      return [];
    }
  };

  const fetchOfficeOptions = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/v1/options/office');
      const result = await response.json();
      const optionsData = result.data || [];
      setOfficeOptions(optionsData);
      return optionsData;
    } catch (err) {
      console.error('Error fetching Office options:', err);
      setOfficeOptions([]);
      return [];
    }
  };

  const fetchAntivirusOptions = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/v1/options/antivirus');
      const result = await response.json();
      const optionsData = result.data || [];
      setAntivirusOptions(optionsData);
      return optionsData;
    } catch (err) {
      console.error('Error fetching Antivirus options:', err);
      setAntivirusOptions([]);
      return [];
    }
  };

  const fetchSoftwareOptions = async () => {
    try {
      const response = await fetch('http://localhost:5000/api/v1/options/software');
      const result = await response.json();
      const optionsData = result.data || [];
      setSoftwareOptions(optionsData);
      return optionsData;
    } catch (err) {
      console.error('Error fetching Software options:', err);
      setSoftwareOptions([]);
      return [];
    }
  };

  // Modal handlers for adding new options
  const handleOpenAddModal = (type) => {
    setModalType(type);
    setNewOptionValue('');
    setShowAddModal(true);
  };

  const handleCloseAddModal = () => {
    setShowAddModal(false);
    setModalType('');
    setNewOptionValue('');
    setAddingOption(false);
  };

  const handleAddNewOption = async () => {
    if (!newOptionValue.trim()) {
      alert('Please enter a value');
      return;
    }

    setAddingOption(true);
    try {
      let endpoint = '';
      let updateStateFunction = null;
      let autoSelectField = '';
      let requestBody = {};

      // Determine endpoint and state update function based on modalType
      if (modalType === 'category') {
        endpoint = '/categories';
        updateStateFunction = setCategories;
        autoSelectField = 'category';
        requestBody = { name: newOptionValue.trim() };
      } else if (modalType === 'model') {
        endpoint = '/models';
        updateStateFunction = setModels;
        autoSelectField = 'model';
        requestBody = { name: newOptionValue.trim() };
      } else if (modalType === 'peripheral') {
        endpoint = '/peripherals/types';
        updateStateFunction = setPeripheralTypes;
        autoSelectField = 'peripheral_name';
        requestBody = { name: newOptionValue.trim() };
      } else if (modalType === 'windows') {
        endpoint = '/options/windows';
        updateStateFunction = setWindowsOptions;
        autoSelectField = 'windows';
        requestBody = { value: newOptionValue.trim() };
      } else if (modalType === 'office') {
        endpoint = '/options/office';
        updateStateFunction = setOfficeOptions;
        autoSelectField = 'microsoft_office';
        requestBody = { value: newOptionValue.trim() };
      } else if (modalType === 'antivirus') {
        endpoint = '/options/antivirus';
        updateStateFunction = setAntivirusOptions;
        autoSelectField = 'antivirus';
        requestBody = { value: newOptionValue.trim() };
      } else if (modalType === 'software') {
        endpoint = '/options/software';
        updateStateFunction = setSoftwareOptions;
        autoSelectField = 'software';
        requestBody = { value: newOptionValue.trim() };
      }

      const response = await fetch(`http://localhost:5000/api/v1${endpoint}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(requestBody),
      });

      const result = await response.json();

      // Handle both success (201) and conflict (409 - already exists)
      if ((response.ok && result.success) || response.status === 409) {
        let selectedValue = newOptionValue.trim();
        
        // If 409 conflict, refresh dropdown to get the existing item from database
        if (response.status === 409) {
          console.log(`✅ ${modalType} "${selectedValue}" already exists, refreshing dropdown...`);
          
          // Refresh the appropriate dropdown list and get the returned data
          let refreshedData = [];
          if (modalType === 'category') {
            refreshedData = await fetchCategories();
            console.log('📋 Categories state after fetch:', refreshedData);
          } else if (modalType === 'model') {
            refreshedData = await fetchModels();
            console.log('📋 Models state after fetch:', refreshedData);
          } else if (modalType === 'peripheral') {
            refreshedData = await fetchPeripheralTypes();
            console.log('📋 Peripheral types state after fetch:', refreshedData);
          } else if (modalType === 'windows') {
            refreshedData = await fetchWindowsOptions();
            console.log('📋 Windows options state after fetch:', refreshedData);
          } else if (modalType === 'office') {
            refreshedData = await fetchOfficeOptions();
            console.log('📋 Office options state after fetch:', refreshedData);
          } else if (modalType === 'antivirus') {
            refreshedData = await fetchAntivirusOptions();
            console.log('📋 Antivirus options state after fetch:', refreshedData);
          } else if (modalType === 'software') {
            refreshedData = await fetchSoftwareOptions();
            console.log('📋 Software options state after fetch:', refreshedData);
          }
          
          console.log(`✅ Refreshed ${modalType} dropdown with ${refreshedData.length} items`);
          
          // Wait a bit for state to fully update
          await new Promise(resolve => setTimeout(resolve, 100));
          
          // For object arrays, find the exact matching item
          if (['category', 'model', 'peripheral'].includes(modalType)) {
            const matchingItem = refreshedData.find(item => {
              const itemName = item.Category || item.Model_Name || item.Model || item.Peripheral_Type_Name || item.name || '';
              return itemName.toLowerCase() === selectedValue.toLowerCase();
            });
            
            if (matchingItem) {
              selectedValue = matchingItem.Category || matchingItem.Model_Name || matchingItem.Model || matchingItem.Peripheral_Type_Name || matchingItem.name;
              console.log(`✅ Found matching ${modalType}:`, selectedValue);
            }
          }
        } else {
          // Success case - add new option to dropdown
          const newOption = result.data;
          
          // For simple string arrays (windows, office, antivirus, software)
          if (['windows', 'office', 'antivirus', 'software'].includes(modalType)) {
            updateStateFunction(prev => [...prev, newOption]);
            selectedValue = newOption;
          } else {
            // For object arrays (category, model, peripheral)
            updateStateFunction(prev => [...prev, newOption]);
            
            if (modalType === 'category') {
              selectedValue = newOption.Category || newOption.name;
            } else if (modalType === 'model') {
              selectedValue = newOption.Model_Name || newOption.Model || newOption.name;
            } else if (modalType === 'peripheral') {
              selectedValue = newOption.Peripheral_Type_Name || newOption.name;
            }
          }
          
          console.log(`✅ Added new ${modalType}:`, selectedValue);
        }

        // Auto-select the value in the form
        setAsset(prevAsset => ({
          ...prevAsset,
          [autoSelectField]: selectedValue
        }));
        
        console.log(`✅ Auto-selected ${autoSelectField}:`, selectedValue);

        handleCloseAddModal();
      } else {
        alert(result.error || 'Failed to add new option');
        setAddingOption(false);
      }
    } catch (error) {
      console.error('Error adding new option:', error);
      alert('Failed to add new option. Please try again.');
      setAddingOption(false);
    }
  };

  const handleSubmitClick = (e) => {
    e.preventDefault();
    
    // Validate form before showing confirmation
    if (!projectData.project_reference_num.trim()) {
      setError('Please enter a project reference number');
      return;
    }
    
    if (!selectedBranch) {
      setError('Please select a branch');
      return;
    }
    
    if (!asset.serial_number.trim() || !asset.tag_id.trim() || !asset.item_name.trim()) {
      setError('Please fill in all required asset fields');
      return;
    }

    // Validate peripheral data
    const peripheralErrors = validatePeripherals();
    if (peripheralErrors.length > 0) {
      setError(`Peripheral validation errors:\n${peripheralErrors.join('\n')}`);
      return;
    }
    
    // Clear any previous errors and show confirmation
    setError(null);
    setShowCreateConfirmation(true);
  };

  const handleConfirmCreate = async () => {
    setLoading(true);
    setError(null);
    
    try {
      // Prepare complete asset data
      const completeAssetData = {
        // Project and customer info
        project_reference_num: projectData.project_reference_num,
        customer_name: projectData.customer_name,
        customer_reference_number: projectData.customer_reference_number,
        branch: selectedBranch,
        
        // Asset info
        serial_number: asset.serial_number,
        tag_id: asset.tag_id,
        item_name: asset.item_name,
        category: asset.category,
        model: asset.model,
        status: asset.status,
        recipient_name: asset.recipient_name,
        department_name: asset.department_name,
        position: asset.position,
        
        // New fields
        windows: asset.windows || null,
        microsoft_office: asset.microsoft_office || null,
        software: asset.software || null,
        monthly_prices: asset.monthly_prices || null,
        
        // Include only valid peripherals (those with both name and serial code)
        peripherals: peripherals.filter(p => p.peripheral_name.trim() && p.serial_code_name.trim())
      };
      
      console.log('Submitting asset data:', completeAssetData);
      
      const response = await apiService.createAssetWithDetails(completeAssetData);
      console.log('Asset created successfully:', response);
      
      if (response.success) {
        setAutoGenerated({
          asset_id: response.data.asset_id,
          pmid: response.data.pmid,
          inventory_id: response.data.inventory_id
        });
        setSuccess(true);
        setShowCreateConfirmation(false);
        
        // Navigate with state to trigger refresh on Assets page
        setTimeout(() => {
          navigate('/assets', { 
            state: { 
              refresh: true, 
              message: 'Asset created successfully',
              newAssetId: response.data.asset_id 
            },
            replace: false  // Use push instead of replace to ensure proper navigation
          });
        }, 2000);
      } else {
        setError(response.message || 'Failed to create asset');
        setLoading(false);
        setShowCreateConfirmation(false);
      }
      
    } catch (err) {
      console.error('Error creating asset:', err);
      setError(err.message || 'Failed to create asset');
      setLoading(false);
      setShowCreateConfirmation(false);
    }
  };

  const handleCancelClick = () => {
    setShowCancelConfirmation(true);
  };

  const handleConfirmCancel = () => {
    navigate('/assets');
  };

  const handleAssetChange = (e) => {
    setAsset({ ...asset, [e.target.name]: e.target.value });
  };

  const handleProjectRefChange = (e) => {
    const value = e.target.value;
    
    // Mark that user has interacted with the field
    if (!userHasInteracted && value.length > 0) {
      setUserHasInteracted(true);
    }
    
    setProjectSearchTerm(value);
    setProjectData(prev => ({
      ...prev,
      project_reference_num: value
    }));
    setShowProjectDropdown(value.length > 0);
    
    // Clear previous search errors when user types
    if (projectSearchError && value.length > 0) {
      setProjectSearchError(null);
    }
  };

  const handleProjectSelect = (project) => {
    setUserHasInteracted(true); // User has interacted by selecting
    setProjectSearchError(null); // Clear any errors
    
    // Set project data with fresh values (don't spread old projectData to avoid stale state)
    setProjectData({
      project_reference_num: project.Project_Ref_Number || '',
      customer_name: project.Customer_Name || '',
      customer_reference_number: project.Customer_Ref_Number || '',
      project_title: project.Project_Title || ''
    });
    setProjectSearchTerm(project.Project_Ref_Number || '');
    setShowProjectDropdown(false);
    
    // Auto-populate antivirus from project if available
    if (project.Antivirus) {
      setAsset(prev => ({
        ...prev,
        antivirus: project.Antivirus
      }));
    }
    
    // Trigger branch fetching if customer name is available
    if (project.Customer_Name) {
      fetchBranchesByCustomer(project.Customer_Name);
    }
  };

  const handleProjectInputFocus = () => {
    setUserHasInteracted(true); // Mark interaction when user focuses
    setShowProjectDropdown(true);
  };

  const handleProjectInputBlur = () => {
    // Delay hiding dropdown to allow for clicks
    setTimeout(() => setShowProjectDropdown(false), 300);
  };

  // Helper function to check if a peripheral form is complete
  const isPeripheralComplete = (peripheral) => {
    return peripheral.peripheral_name.trim() !== '' && peripheral.serial_code_name.trim() !== '';
  };

  // Helper function to check if we can add a new peripheral
  const canAddNewPeripheral = () => {
    if (peripherals.length === 0) return true;
    const lastPeripheral = peripherals[peripherals.length - 1];
    return isPeripheralComplete(lastPeripheral);
  };

  // Enhanced peripheral validation for submission
  const validatePeripherals = () => {
    const errors = [];
    peripherals.forEach((peripheral, index) => {
      if (peripheral.peripheral_name.trim() && !peripheral.serial_code_name.trim()) {
        errors.push(`Peripheral ${index + 1}: Serial code is required when peripheral name is provided`);
      }
    });
    return errors;
  };

  const handlePeripheralChange = (index, field, value) => {
    const updatedPeripherals = [...peripherals];
    updatedPeripherals[index][field] = value;
    setPeripherals(updatedPeripherals);
  };

  const addPeripheral = () => {
    // Only allow adding if current peripheral forms are complete
    if (canAddNewPeripheral()) {
      setPeripherals([...peripherals, {
        peripheral_name: '',
        serial_code_name: '',
        condition: 'Good',
        remarks: ''
      }]);
    }
  };

  const removePeripheral = (index) => {
    if (peripherals.length > 1) {
      const updatedPeripherals = peripherals.filter((_, i) => i !== index);
      setPeripherals(updatedPeripherals);
    }
  };

  if (success) {
    return (
      <div style={{ textAlign: 'center', padding: '40px' }}>
        <div style={{ 
          backgroundColor: '#d4edda', 
          color: '#155724', 
          padding: '20px', 
          borderRadius: '8px',
          maxWidth: '500px',
          margin: '0 auto'
        }}>
          <h2 style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px' }}>
            <CheckCircle size={28} color="#28a745" />
            Asset Created Successfully!
          </h2>
          <p>Asset ID: {autoGenerated.asset_id}</p>
          <p>PMID: {autoGenerated.pmid}</p>
          <p>Inventory ID: {autoGenerated.inventory_id}</p>
          <p>Redirecting to assets page...</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <style jsx>{`
        .dropdown-container {
          position: relative;
          z-index: 1000;
        }
        
        .dropdown-menu {
          position: absolute;
          top: 100%;
          left: 0;
          right: 0;
          background: white;
          border: 1px solid #ddd;
          border-radius: 8px;
          box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
          max-height: 250px;
          overflow-y: auto;
          z-index: 1001;
          margin-top: 4px;
        }
        
        .dropdown-item {
          padding: 12px 16px;
          border-bottom: 1px solid #f0f0f0;
          cursor: pointer;
          transition: background-color 0.2s ease;
        }
        
        .dropdown-item:hover {
          background-color: #f8f9fa !important;
        }
        
        .dropdown-item:last-child {
          border-bottom: none;
        }
        
        .dropdown-ref-number {
          font-weight: 600;
          color: #333;
          margin-bottom: 4px;
        }
        
        .dropdown-title {
          font-size: 14px;
          color: #666;
          margin-bottom: 2px;
        }
        
        .dropdown-customer {
          font-size: 12px;
          color: #888;
        }
      `}</style>
      
      <div style={{ display: 'flex', alignItems: 'center', marginBottom: '20px' }}>
        <button onClick={() => navigate('/assets')} className="btn btn-secondary" style={{ marginRight: '15px' }}>
          <ArrowLeft size={16} />
        </button>
        <h1>Add New Asset</h1>
      </div>

      {error && (
        <div style={{ 
          backgroundColor: '#f8d7da', 
          color: '#721c24', 
          padding: '15px', 
          borderRadius: '8px',
          marginBottom: '20px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px'
        }}>
          <AlertCircle size={20} />
          {error}
        </div>
      )}

      {projectSearchError && userHasInteracted && (
        <div style={{ 
          backgroundColor: '#fff3cd', 
          color: '#856404', 
          padding: '12px', 
          borderRadius: '6px',
          marginBottom: '15px',
          border: '1px solid #ffeaa7',
          display: 'flex',
          alignItems: 'center',
          gap: '8px'
        }}>
          <AlertCircle size={18} />
          {projectSearchError}
        </div>
      )}

      <div className="card">
        <form onSubmit={handleSubmitClick}>
          
          {/* Project Reference Section */}
          <div style={{ 
            backgroundColor: '#e8f5e8', 
            padding: '20px', 
            borderRadius: '8px', 
            marginBottom: '25px',
            border: '2px solid #4caf50'
          }}>
            <h3 style={{ 
              color: '#2e7d32', 
              marginBottom: '15px', 
              display: 'flex', 
              alignItems: 'center', 
              gap: '10px' 
            }}>
              <Hash size={20} />
              Step 1: Project Reference Number
            </h3>
            
            <div className="form-group">
              <label>Current Project Reference Number *</label>
              <div className="dropdown-container">
                <input
                  type="text"
                  value={projectSearchTerm}
                  onChange={handleProjectRefChange}
                  onFocus={handleProjectInputFocus}
                  onBlur={handleProjectInputBlur}
                  placeholder="Start typing project reference number..."
                  required
                  style={{ fontSize: '16px', fontWeight: 'bold', width: '100%' }}
                  autoComplete="off"
                />
                
                {showProjectDropdown && filteredProjects.length > 0 && (
                  <div className="dropdown-menu">
                    {filteredProjects.map((project, index) => (
                      <div
                        key={index}
                        className="dropdown-item"
                        onMouseDown={(e) => {
                          e.preventDefault(); // Prevent input blur
                          handleProjectSelect(project);
                        }}
                      >
                        <div className="dropdown-ref-number">
                          {project.Project_Ref_Number}
                        </div>
                        <div className="dropdown-title">
                          {project.Project_Title}
                        </div>
                        <div className="dropdown-customer">
                          Customer: {project.Customer_Name}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
                
                {showProjectDropdown && projectSearchTerm.length > 0 && filteredProjects.length === 0 && (
                  <div className="dropdown-menu">
                    <div style={{ padding: '12px', fontSize: '14px', color: '#666' }}>
                      No projects found matching "{projectSearchTerm}"
                    </div>
                  </div>
                )}
              </div>
              <small style={{ color: '#666', display: 'block', marginTop: '5px' }}>
                Start typing to see available projects, or enter the exact project reference number
              </small>
            </div>

            {/* Auto-populated Project Data (Read-only) */}
            {projectData.customer_name && (
              <div style={{ 
                backgroundColor: '#f0f8f0', 
                padding: '15px', 
                borderRadius: '6px', 
                marginTop: '15px',
                border: '1px solid #c8e6c9'
              }}>
                <h4 style={{ color: '#2e7d32', marginBottom: '10px' }}>Project Information:</h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                  <div>
                    <label style={{ fontWeight: 'bold', color: '#555' }}>Customer Name:</label>
                    <div style={{ padding: '8px', backgroundColor: '#fff', border: '1px solid #ddd', borderRadius: '4px' }}>
                      {projectData.customer_name}
                    </div>
                  </div>
                  <div>
                    <label style={{ fontWeight: 'bold', color: '#555' }}>Customer Reference:</label>
                    <div style={{ padding: '8px', backgroundColor: '#fff', border: '1px solid #ddd', borderRadius: '4px' }}>
                      {projectData.customer_reference_number}
                    </div>
                  </div>
                </div>
                {projectData.project_title && (
                  <div style={{ marginTop: '10px' }}>
                    <label style={{ fontWeight: 'bold', color: '#555' }}>Project Title:</label>
                    <div style={{ padding: '8px', backgroundColor: '#fff', border: '1px solid #ddd', borderRadius: '4px' }}>
                      {projectData.project_title}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Branch Selection Section */}
          {projectData.customer_name && (
            <div style={{ 
              backgroundColor: '#e3f2fd', 
              padding: '20px', 
              borderRadius: '8px', 
              marginBottom: '25px',
              border: '2px solid #2196f3'
            }}>
              <h3 style={{ 
                color: '#1976d2', 
                marginBottom: '15px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px' 
              }}>
                <MapPin size={20} />
                Step 2: Branch Selection
              </h3>
              
              <div className="form-group">
                <label>Select Branch *</label>
                
                {loading ? (
                  <div style={{ 
                    padding: '10px', 
                    backgroundColor: '#f5f5f5', 
                    border: '1px solid #ddd', 
                    borderRadius: '4px',
                    textAlign: 'center',
                    color: '#666',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '8px'
                  }}>
                    <Loader size={16} style={{ animation: 'spin 1s linear infinite' }} />
                    <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
                    Loading branches...
                  </div>
                ) : (
                  <select 
                    value={selectedBranch} 
                    onChange={(e) => setSelectedBranch(e.target.value)}
                    required
                    disabled={!projectData.customer_name || loading}
                    style={{ 
                      backgroundColor: !projectData.customer_name ? '#f5f5f5' : 'white',
                      opacity: !projectData.customer_name ? 0.7 : 1
                    }}
                  >
                    <option value="">
                      {branches.length === 0 
                        ? 'No branches available' 
                        : 'Select Branch'
                      }
                    </option>
                    {branches.map((branch, index) => (
                      <option key={index} value={branch.Branch}>
                        {branch.Branch}
                        {branch.Customer_ID && branch.Customer_ID.toString().startsWith('temp_') && ' (Default)'}
                        {branch.Customer_ID && branch.Customer_ID.toString().startsWith('fallback_') && ' (Fallback)'}
                      </option>
                    ))}
                  </select>
                )}
                
                {!projectData.customer_name && (
                  <small style={{ color: '#666', fontSize: '12px' }}>
                    Customer name must be populated first
                  </small>
                )}
                
                {branches.length > 0 && (
                  <small style={{ color: '#666', fontSize: '12px', display: 'block', marginTop: '5px' }}>
                    Found {branches.length} branch{branches.length !== 1 ? 'es' : ''} for {projectData.customer_name}
                  </small>
                )}
              </div>
            </div>
          )}

          {/* User-Provided Asset Data Section */}
          {selectedBranch && (
            <div style={{ 
              backgroundColor: '#f3e5f5', 
              padding: '20px', 
              borderRadius: '8px', 
              marginBottom: '25px',
              border: '2px solid #9c27b0'
            }}>
              <h3 style={{ 
                color: '#7b1fa2', 
                marginBottom: '15px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px' 
              }}>
                <Package size={20} />
                Step 3: Asset Information
              </h3>
              
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div className="form-group">
                  <label>Serial Number *</label>
                  <input
                    type="text"
                    name="serial_number"
                    value={asset.serial_number}
                    onChange={handleAssetChange}
                    placeholder="78HT574"
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Tag ID *</label>
                  <input
                    type="text"
                    name="tag_id"
                    value={asset.tag_id}
                    onChange={handleAssetChange}
                    placeholder="NADMA-A25001"
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Item Name *</label>
                  <input
                    type="text"
                    name="item_name"
                    value={asset.item_name}
                    onChange={handleAssetChange}
                    placeholder="Komputer Meja (All-in-One)"
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Status</label>
                  <select name="status" value={asset.status} onChange={handleAssetChange}>
                    <option value="Active">Active</option>
                    <option value="Inactive">Inactive</option>
                    <option value="Maintenance">Maintenance</option>
                    <option value="Retired">Retired</option>
                  </select>
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>
                      Category <span style={{ color: '#f44336' }}>*</span>
                    </span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('category')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.category}
                    onChange={(e) => setAsset({ ...asset, category: e.target.value })}
                    required
                  >
                    <option value="">Select category</option>
                    {categories.map((cat, index) => {
                      const catValue = cat.Category || cat;
                      return (
                        <option key={`cat-${catValue}-${index}`} value={catValue}>
                          {catValue}
                        </option>
                      );
                    })}
                  </select>
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>
                      Model <span style={{ color: '#f44336' }}>*</span>
                    </span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('model')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.model}
                    onChange={(e) => setAsset({ ...asset, model: e.target.value })}
                    required
                  >
                    <option value="">Select model</option>
                    {models.map((mod, index) => {
                      const modValue = mod.Model_Name || mod.Model || mod;
                      return (
                        <option key={`mod-${modValue}-${index}`} value={modValue}>
                          {modValue}
                        </option>
                      );
                    })}
                  </select>
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>Windows</span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('windows')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.windows}
                    onChange={(e) => setAsset({ ...asset, windows: e.target.value })}
                  >
                    <option value="">Select Windows version</option>
                    {windowsOptions.map((win, index) => (
                      <option key={`win-${win}-${index}`} value={win}>
                        {win}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>Microsoft Office</span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('office')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.microsoft_office}
                    onChange={(e) => setAsset({ ...asset, microsoft_office: e.target.value })}
                  >
                    <option value="">Select Office version</option>
                    {officeOptions.map((office, index) => (
                      <option key={`office-${office}-${index}`} value={office}>
                        {office}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>Antivirus</span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('antivirus')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.antivirus}
                    onChange={(e) => setAsset({ ...asset, antivirus: e.target.value })}
                  >
                    <option value="">Select antivirus</option>
                    {antivirusOptions.map((av, index) => (
                      <option key={`av-${av}-${index}`} value={av}>
                        {av}
                      </option>
                    ))}
                  </select>
                  {projectData.project_reference_num && asset.antivirus && (
                    <small style={{ color: '#666', fontSize: '11px', marginTop: '4px', display: 'block' }}>
                       Auto-populated 
                    </small>
                  )}
                </div>

                <div className="form-group">
                  <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>Software</span>
                    <button
                      type="button"
                      onClick={() => handleOpenAddModal('software')}
                      style={{
                        background: '#4caf50',
                        color: 'white',
                        border: 'none',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        cursor: 'pointer',
                        fontSize: '12px',
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}
                    >
                      <Plus size={14} /> 
                    </button>
                  </label>
                  <select
                    value={asset.software}
                    onChange={(e) => setAsset({ ...asset, software: e.target.value })}
                  >
                    <option value="">Select software</option>
                    <option value="None">None</option>
                    {softwareOptions.map((sw, index) => (
                      <option key={`sw-${sw}-${index}`} value={sw}>
                        {sw}
                      </option>
                    ))}
                  </select>
                </div>

                <div className="form-group">
                  <label>Monthly Price</label>
                  <input
                    type="text"
                    name="monthly_prices"
                    value={asset.monthly_prices}
                    onChange={handleAssetChange}
                    placeholder="e.g., 150.00"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Recipient Information Section */}
          {selectedBranch && (
            <div style={{ 
              backgroundColor: '#fff3e0', 
              padding: '20px', 
              borderRadius: '8px', 
              marginBottom: '25px',
              border: '2px solid #ff9800'
            }}>
              <h3 style={{ 
                color: '#f57c00', 
                marginBottom: '15px', 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px' 
              }}>
                <User size={20} />
                Step 4: Recipient Information
              </h3>
              
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                <div className="form-group">
                  <label>Recipient Name *</label>
                  <input
                    type="text"
                    name="recipient_name"
                    value={asset.recipient_name}
                    onChange={handleAssetChange}
                    placeholder="Insp Abdullah bin Ahmad Sobri"
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Department Name *</label>
                  <input
                    type="text"
                    name="department_name"
                    value={asset.department_name}
                    onChange={handleAssetChange}
                    placeholder="Ketua SHU C (ETK) Ajutan"
                    required
                  />
                </div>

                <div className="form-group">
                  <label>Position</label>
                  <input
                    type="text"
                    name="position"
                    value={asset.position}
                    onChange={handleAssetChange}
                    placeholder="Manager, Officer"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Peripheral Section */}
          {selectedBranch && (
            <div style={{ 
              backgroundColor: '#e0f2f1', 
              padding: '20px', 
              borderRadius: '8px', 
              marginBottom: '25px',
              border: '2px solid #009688'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                <h3 style={{ 
                  color: '#00695c', 
                  margin: 0,
                  display: 'flex', 
                  alignItems: 'center', 
                  gap: '10px' 
                }}>
                  <Wrench size={20} />
                  Step 5: Peripherals (Optional)
                </h3>
                <button 
                  type="button" 
                  onClick={addPeripheral} 
                  className={`btn ${canAddNewPeripheral() ? 'btn-secondary' : 'btn-disabled'}`}
                  disabled={!canAddNewPeripheral()}
                  style={{ 
                    padding: '8px 12px', 
                    fontSize: '14px',
                    opacity: canAddNewPeripheral() ? 1 : 0.5,
                    cursor: canAddNewPeripheral() ? 'pointer' : 'not-allowed'
                  }}
                  title={!canAddNewPeripheral() ? 'Complete the current peripheral form before adding another' : 'Add a new peripheral'}
                >
                  <Plus size={14} style={{ marginRight: '5px' }} />
                  Add Peripheral
                </button>
              </div>

              {!canAddNewPeripheral() && peripherals.length > 0 && (
                <div style={{
                  backgroundColor: '#fff3cd',
                  color: '#856404',
                  padding: '8px 12px',
                  borderRadius: '4px',
                  fontSize: '12px',
                  marginBottom: '15px',
                  border: '1px solid #ffeaa7',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px'
                }}>
                  <Lightbulb size={16} />
                  Complete the current peripheral form (name and serial code required) before adding another
                </div>
              )}
              
              {peripherals.map((peripheral, index) => (
                <div key={index} style={{ 
                  backgroundColor: '#f0f8f0', 
                  padding: '15px', 
                  borderRadius: '6px', 
                  marginBottom: '15px',
                  border: '1px solid #b2dfdb'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                    <h4 style={{ color: '#00695c', margin: 0 }}>Peripheral {index + 1}</h4>
                    {peripherals.length > 1 && (
                      <button 
                        type="button" 
                        onClick={() => removePeripheral(index)}
                        style={{ 
                          background: 'none', 
                          border: 'none', 
                          color: '#f44336', 
                          cursor: 'pointer',
                          padding: '5px'
                        }}
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                  </div>
                  
                  <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '15px' }}>
                    <div className="form-group" style={{ marginBottom: '10px' }}>
                      <label style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <span>
                          Peripheral Name
                          {peripheral.peripheral_name.trim() !== '' && <span style={{ color: '#4caf50' }}> ✓</span>}
                        </span>
                        <button
                          type="button"
                          onClick={() => handleOpenAddModal('peripheral')}
                          style={{
                            background: '#4caf50',
                            color: 'white',
                            border: 'none',
                            padding: '4px 8px',
                            borderRadius: '4px',
                            cursor: 'pointer',
                            fontSize: '12px',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '4px'
                          }}
                        >
                          <Plus size={14} />
                        </button>
                      </label>
                      <select
                        value={peripheral.peripheral_name}
                        onChange={(e) => handlePeripheralChange(index, 'peripheral_name', e.target.value)}
                        className={peripheral.peripheral_name.trim() && !peripheral.serial_code_name.trim() ? 'peripheral-warning' : ''}
                      >
                        <option value="">Select peripheral type</option>
                        {peripheralTypes.map((type, idx) => {
                          const typeValue = type.Peripheral_Type_Name || type;
                          return (
                            <option key={`ptype-${typeValue}-${idx}`} value={typeValue}>
                              {typeValue}
                            </option>
                          );
                        })}
                      </select>
                    </div>

                    <div className="form-group" style={{ marginBottom: '10px' }}>
                      <label>
                        Serial Code
                        {peripheral.peripheral_name.trim() !== '' && (
                          <span style={{ color: '#f44336' }}> * (Required)</span>
                        )}
                        {peripheral.serial_code_name.trim() !== '' && <span style={{ color: '#4caf50' }}> ✓</span>}
                      </label>
                      <input
                        type="text"
                        value={peripheral.serial_code_name}
                        onChange={(e) => handlePeripheralChange(index, 'serial_code_name', e.target.value)}
                        placeholder="CN-GE90-9865"
                        style={{
                          borderColor: peripheral.peripheral_name.trim() && !peripheral.serial_code_name.trim() ? '#ff9800' : ''
                        }}
                      />
                      {peripheral.peripheral_name.trim() && !peripheral.serial_code_name.trim() && (
                        <small style={{ color: '#ff9800', fontSize: '11px', display: 'block', marginTop: '2px' }}>
                          Serial code is required when peripheral name is selected
                        </small>
                      )}
                    </div>

                    <div className="form-group" style={{ marginBottom: '10px' }}>
                      <label>Condition</label>
                      <select 
                        value={peripheral.condition} 
                        onChange={(e) => handlePeripheralChange(index, 'condition', e.target.value)}
                      >
                        <option value="Good">Good</option>
                        <option value="Fair">Fair</option>
                        <option value="Poor">Poor</option>
                        <option value="Needs Repair">Needs Repair</option>
                      </select>
                    </div>

                    <div className="form-group" style={{ marginBottom: '10px' }}>
                      <label>Remarks</label>
                      <input
                        type="text"
                        value={peripheral.remarks}
                        onChange={(e) => handlePeripheralChange(index, 'remarks', e.target.value)}
                        placeholder="Optional remarks"
                      />
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}



          <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
            <button 
              type="submit" 
              className="btn btn-primary"
              disabled={loading || !selectedBranch}
              style={{ 
                padding: '12px 24px',
                fontSize: '16px',
                fontWeight: 'bold'
              }}
            >
              <Save size={16} style={{ marginRight: '8px' }} />
              {loading ? 'Creating Asset...' : 'Create Asset'}
            </button>
            <button 
              type="button" 
              onClick={handleCancelClick}
              className="btn btn-secondary"
              disabled={loading}
              style={{ 
                padding: '12px 24px',
                fontSize: '16px'
              }}
            >
              Cancel
            </button>
          </div>
        </form>
      </div>

      {/* Create Asset Confirmation Modal */}
      <ConfirmationModal
        isOpen={showCreateConfirmation}
        onClose={() => setShowCreateConfirmation(false)}
        onConfirm={handleConfirmCreate}
        title="Create New Asset"
        message="Are you sure you want to create this new asset? Please review the information below before confirming."
        confirmText="Create Asset"
        cancelText="Review"
        type="success"
        showSummary={true}
        summaryData={{
          projectRef: projectData.project_reference_num,
          customer: projectData.customer_name,
          branch: selectedBranch,
          serialNumber: asset.serial_number,
          tagId: asset.tag_id,
          itemName: asset.item_name,
          category: asset.category,
          model: asset.model,
          peripheralCount: peripherals.filter(p => p.peripheral_name.trim() && p.serial_code_name.trim()).length
        }}
        loading={loading}
      />

      {/* Cancel Confirmation Modal */}
      <ConfirmationModal
        isOpen={showCancelConfirmation}
        onClose={() => setShowCancelConfirmation(false)}
        onConfirm={handleConfirmCancel}
        title="Cancel Asset Creation"
        message="Are you sure you want to cancel? All entered data will be lost and cannot be recovered."
        confirmText="Yes, Cancel"
        cancelText="Continue Editing"
        type="danger"
      />

      {/* Add New Option Modal */}
      {showAddModal && (
        <div 
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            zIndex: 1000
          }}
          onClick={handleCloseAddModal}
        >
          <div 
            style={{
              backgroundColor: 'white',
              padding: '25px',
              borderRadius: '8px',
              minWidth: '400px',
              maxWidth: '500px',
              boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)'
            }}
            onClick={(e) => e.stopPropagation()}
          >
            <div style={{ marginBottom: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <h3 style={{ margin: 0, color: '#333' }}>
                Add New {
                  modalType === 'category' ? 'Category' : 
                  modalType === 'model' ? 'Model' : 
                  modalType === 'peripheral' ? 'Peripheral Type' :
                  modalType === 'windows' ? 'Windows Version' :
                  modalType === 'office' ? 'Office Version' :
                  modalType === 'antivirus' ? 'Antivirus' :
                  modalType === 'software' ? 'Software' : ''
                }
              </h3>
              <button
                onClick={handleCloseAddModal}
                style={{
                  background: 'none',
                  border: 'none',
                  fontSize: '24px',
                  cursor: 'pointer',
                  color: '#666',
                  padding: '0',
                  lineHeight: '1'
                }}
              >
                ×
              </button>
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', marginBottom: '8px', color: '#555', fontWeight: '500' }}>
                {
                  modalType === 'category' ? 'Category' : 
                  modalType === 'model' ? 'Model' : 
                  modalType === 'peripheral' ? 'Peripheral Type' :
                  modalType === 'windows' ? 'Windows Version' :
                  modalType === 'office' ? 'Office Version' :
                  modalType === 'antivirus' ? 'Antivirus' :
                  modalType === 'software' ? 'Software' : ''
                } Name
              </label>
              <input
                type="text"
                value={newOptionValue}
                onChange={(e) => setNewOptionValue(e.target.value)}
                onKeyPress={(e) => {
                  if (e.key === 'Enter' && !addingOption) {
                    handleAddNewOption();
                  }
                }}
                placeholder={
                  modalType === 'category' ? 'e.g., Desktop, Laptop, Server' : 
                  modalType === 'model' ? 'e.g., Dell OptiPlex 7420, HP EliteBook' : 
                  modalType === 'peripheral' ? 'e.g., Monitor, Keyboard, Mouse' :
                  modalType === 'windows' ? 'e.g., Windows 10 Pro, Windows 11' :
                  modalType === 'office' ? 'e.g., Office 2019, Microsoft 365' :
                  modalType === 'antivirus' ? 'e.g., Kaspersky, Norton, McAfee' :
                  modalType === 'software' ? 'e.g., Adobe Acrobat, AutoCAD' : ''
                }
                style={{
                  width: '100%',
                  padding: '10px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px',
                  boxSizing: 'border-box'
                }}
                autoFocus
                disabled={addingOption}
              />
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button
                type="button"
                onClick={handleCloseAddModal}
                disabled={addingOption}
                style={{
                  padding: '10px 20px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  backgroundColor: 'white',
                  color: '#666',
                  cursor: addingOption ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  opacity: addingOption ? 0.5 : 1
                }}
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleAddNewOption}
                disabled={addingOption || !newOptionValue.trim()}
                style={{
                  padding: '10px 20px',
                  border: 'none',
                  borderRadius: '4px',
                  backgroundColor: addingOption || !newOptionValue.trim() ? '#ccc' : '#4caf50',
                  color: 'white',
                  cursor: addingOption || !newOptionValue.trim() ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '5px'
                }}
              >
                {addingOption ? 'Adding...' : 'Add'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default AddAsset;